spring:
  datasource:
    username: root
    password: 1997wxc
    url: jdbc:mysql://localhost:3306/dvdrentdb?serverTimezone=HongKong&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: securitymybatis.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
